[ 2023-04-23 16:42:16,649 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2023-04-23 16:42:16,650 ] root - INFO - Starting data ingestion
[ 2023-04-23 16:42:16,773 ] root - INFO - Consider Local csv file
[ 2023-04-23 16:42:17,930 ] root - INFO - Shape of dataframe: (36188, 171)
[ 2023-04-23 16:42:18,005 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 16:42:18,006 ] root - INFO - Saving exported data into feature store file path: artifact/04_23_2023_16_42_10/data_ingestion/feature_store/sensor.csv
[ 2023-04-23 16:42:18,969 ] root - INFO - Shape of dataframe: (36188, 164)
[ 2023-04-23 16:42:18,969 ] root - INFO - Starting the train and test splittings
[ 2023-04-23 16:42:20,743 ] root - INFO - Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact/04_23_2023_16_42_10/data_ingestion/ingested/train.csv', test_file_path='artifact/04_23_2023_16_42_10/data_ingestion/ingested/test.csv')
[ 2023-04-23 16:42:23,075 ] root - INFO - Missing numerical column: []
[ 2023-04-23 16:42:23,075 ] root - INFO - Valid Numerical Column : True
[ 2023-04-23 16:42:23,076 ] root - INFO - Missing numerical column: []
[ 2023-04-23 16:42:23,076 ] root - INFO - Required number of columns: 164
[ 2023-04-23 16:42:23,076 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 16:42:23,076 ] root - INFO - Required number of columns: 164
[ 2023-04-23 16:42:23,076 ] root - INFO - Data frame has columns: 164
[ 2023-04-23 16:42:38,962 ] root - INFO - Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/main.py] line number [8] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [80] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/pipeline/training_pipeline.py] line number [49] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_validation.py] line number [181] error message [Error occurred python script name [/home/suyodhan/Documents/Data Science Project/current_project/Heyyyyyy/sensor/components/data_validation.py] line number [117] error message ['<' not supported between instances of 'float' and 'str']]]]]
